baseURL = 'https://liangzhongkai.github.io'
languageCode = 'zh'
defaultContentLanguage = "zh"
theme = "ananke"
publishDir = "docs"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[languages]
  [languages.zh]
    title = "阿凯"
    weight = 1
    contentDir = "content/zh"
  [languages.en]
    title = "kevin leung"
    weight = 2
    contentDir = "content/en"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "liangzhongkai/liangzhongkai.github.io"
  issueTerm = "title"
  theme = "github-light"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/liangzhongkai"

[[params.contract]]
email = "https://formspree.io/f/mnqyajey"