baseURL = 'https://liangzhongkai.github.io'
languageCode = 'en-us'
title = 'Kevin Leung'
theme = "ananke"
publishDir = "docs"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "liangzhongkai/liangzhongkai.github.io"
  issueTerm = "title"
  theme = "github-light"